
#ifndef PASSTHRUDEF_H
#define PASSTHRUDEF_H

#include <stdint.h>

typedef struct {
  unsigned long ProtocolID;
  unsigned long RxStatus;
  unsigned long TxFlags;
  unsigned long Timestamp;
  unsigned long DataSize;
  unsigned long ExtraDataIndex;
  unsigned char Data[4128];
} PassThruMsg;

typedef enum {
  GET_CONFIG = 0x1U,
  SET_CONFIG = 0x2U,
  READ_VBATT = 0x3U,
  FIVE_BAUD_INIT = 0x4U,
  FAST_INIT = 0x5U,
  CLEAR_TX_BUFFER = 0x7U,
  CLEAR_RX_BUFFER = 0x8U,
  CLEAR_PERIODIC_MSGS = 0x9U,
  CLEAR_MSG_FILTERS = 0xAU,
  CLEAR_FUNCT_MSG_LOOKUP_TABLE = 0xBU,
  ADD_TO_FUNCT_MSG_LOOKUP_TABLE = 0xCU,
  DELETE_FROM_FUNCT_MSG_LOOKUP_TABLE = 0xDU,
  READ_PROG_VOLTAGE = 0xEU
} PassThruIoctlId;

typedef enum {
  STATUS_NOERROR = 0U,
  ERR_NOT_SUPPORTED = 0x1U,
  ERR_INVALID_CHANNEL_ID = 0x2U,
  ERR_INVALID_PROTOCOL_ID = 0x3U,
  ERR_NULL_PARAMETER = 0x4U,
  ERR_INVALID_IOCTL_VALUE = 0x5U,
  ERR_INVALID_FLAGS = 0x6U,
  ERR_FAILED = 0x7U,
  ERR_DEVICE_NOT_CONNECTED = 0x8U,
  ERR_TIMEOUT = 0x9U,
  ERR_INVALID_MSG = 0xAU,
  ERR_INVALID_TIME_INTERVAL = 0xBU,
  ERR_EXCEEDED_LIMIT = 0xCU,
  ERR_INVALID_MSG_ID = 0xDU,
  ERR_DEVICE_IN_USE = 0xEU,
  ERR_INVAILD_IOCTL_ID = 0xFU,
  ERR_BUFFER_EMPTY = 0x10U,
  ERR_BUFFER_FULL = 0x11U,
  ERR_BUFFER_OVERFLOW = 0x12U,
  ERR_PIN_INVALID = 0x13U,
  ERR_CHANNEL_IN_USE = 0x14U,
  ERR_MSG_PROTOCOL_ID = 0x15U,
  ERR_INVALID_FILTER_ID = 0x16U,
  ERR_NO_FLOW_CONTROL = 0x17U,
  ERR_NOT_UNIQUE = 0x18U,
  ERR_INVALID_BAUDATE = 0x19U,
  ERR_INVALID_DEVICE_ID = 0x1AU
} PassThruError;

typedef enum {
  J1850VPW = 0x01U,
  J1850PWM = 0x02U,
  ISO9141 = 0x03U,
  ISO14230 = 0x04U,
  CAN = 0x05U,
  ISO15765 = 0x06U,
  SCI_A_ENGINE = 0x07U,
  SCI_A_TRANS  = 0x08U,
  SCI_B_ENGINE = 0x09U,
  SCI_B_TRANS = 0x0AU,
  MS_CAN = 0x10000U
} PassThruProtocolId;

#endif // PASSTHRUDEF_H
